### ISSUE TITLE
3D Materials BandGap Prediction

### ISSUE THREAD

**Issue by aydinmirac** [usccolumbia/deeperGATGNN#3]
Hi team,

First of all, thank you for creating this project.

I am working on a bandgap prediction with 3D materials with OMDB dataset: https://omdb.mathub.io/

Compared to QM9, molecules in OMDB are much larger. Therefore, some neural networks such as Schnetpack and ALIGNN don't perform well on OMDB because of the number of datapoints and molecule size.

I am just wondering if your neural network supports QM9 or OMDB. Do you have any plan to include 3D datasets in future? Or do you have any suggestions how I can test the NN with different datasets?

Best regards.

**Comment by usccolumbia** [comment]
you just need to write a reading function to convert QM9 SMILES into graph, and then u can use our algorithm.
________________________________
From: MiracAydin1 ***@***.***>
Sent: Monday, April 4, 2022 4:36 PM
To: usccolumbia/deeperGATGNN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usccolumbia/deeperGATGNN] 3D Materials BandGap Prediction (Issue #3)


Hi team,

First of all, thank you for creating this project.

I am working on a bandgap prediction with 3D materials with OMDB dataset: https://omdb.mathub.io/<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-31327df5-454455534531-14abdc6ad47b7fd6&q=1&e=d216b65b-2036-4bf5-aa09-f08c6cc0cf1c&u=https%3A%2F%2Fomdb.mathub.io%2F>

Compared to QM9, molecules in OMDB are much larger. Therefore, some neural networks such as Schnetpack and ALIGNN don't perform well on OMDB because of the number of datapoints and molecule size.

I am just wondering if your neural network supports QM9 or OMDB. Do you have any plan to include 3D datasets in future? Or do you have any suggestions how I can test the NN with different datasets?

Best regards.
