### ISSUE TITLE
Core dumped issue 

### ISSUE THREAD

**Issue by kmr2017** [usccolumbia/deeperGATGNN#6]
I am running the code, but getting below error. 

python main.py --data_path='./data/pt_data/pt_data/' --job_name="job_name" --run_mode='Training' --model='model_name' --epoch='500' --gc_count='20' --save_model='True' --model_path='my_trained_model.pth'
Segmentation fault (core dumped)

**Comment by sadmanomee** [comment]
That is because there is a mismatch in your CUDA, torch, torch-scatter, torch-sparse, torch-cluster, torch-spline-conv, and torch-geometric version. You need to uninstall these first. Then you check your CUDA version and go to this link https://pytorch-geometric.com/whl/index.html and find a version of torch that matches your CUDA. Then install that specific version of torch (with CUDA). Then you install torch-scatter, torch-sparse, torch-cluster, torch-spline-conv for that specific torch and cuda version. Finally, install torch-geometric. Give it a try, I hope this time it will work.

Also use --epochs instead of --epoch in the running command
